# Generated by Django 5.2.11 on 2026-05-04 20:23

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CinemaSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("emoji", models.CharField(default="🎬", max_length=10)),
                ("scheduled_date", models.DateTimeField()),
                (
                    "estimated_duration_minutes",
                    models.IntegerField(blank=True, null=True),
                ),
                ("actual_start_time", models.DateTimeField(blank=True, null=True)),
                ("actual_end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "theme_type",
                    models.CharField(
                        choices=[
                            ("predefined", "Predefined"),
                            ("custom", "Custom"),
                            ("ai_generated", "AI Generated"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "theme_genres",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "theme_countries",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "theme_decades",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "theme_directors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "theme_actors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "theme_moods",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "theme_keywords",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("ai_theme_prompt", models.TextField(blank=True)),
                ("ai_theme_explanation", models.TextField(blank=True)),
                ("min_resolution", models.CharField(default="1080p", max_length=20)),
                ("prefer_remux", models.BooleanField(default=True)),
                ("require_advanced_audio", models.BooleanField(default=False)),
                (
                    "preferred_audio_codecs",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("require_hdr", models.BooleanField(default=False)),
                ("max_file_size_gb", models.IntegerField(blank=True, null=True)),
                ("auto_prepare", models.BooleanField(default=True)),
                ("prepare_hours_before", models.IntegerField(default=24)),
                ("auto_download", models.BooleanField(default=True)),
                ("send_reminders", models.BooleanField(default=True)),
                ("reminder_hours_before", models.IntegerField(default=2)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("preparing", "Preparing"),
                            ("ready", "Ready"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planning",
                        max_length=50,
                    ),
                ),
                ("all_movies_selected", models.BooleanField(default=False)),
                ("all_torrents_found", models.BooleanField(default=False)),
                ("all_downloads_ready", models.BooleanField(default=False)),
                ("playlist_created", models.BooleanField(default=False)),
                ("preparation_progress", models.IntegerField(default=0)),
                ("download_progress", models.IntegerField(default=0)),
                ("plex_playlist_id", models.CharField(blank=True, max_length=100)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "shared_with_users",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "cinema_sessions",
                "ordering": ["-scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="SessionMovie",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("order", models.IntegerField()),
                (
                    "download_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("searching", "Searching"),
                            ("found", "Found"),
                            ("downloading", "Downloading"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("download_progress", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "session_movies",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SessionTheme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("emoji", models.CharField(default="🎬", max_length=10)),
                (
                    "genres",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "countries",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "decades",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "directors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "moods",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "keywords",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("is_predefined", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "session_themes",
                "ordering": ["name"],
            },
        ),
    ]
