# Generated by Django 5.2.11 on 2026-05-04 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("movies", "0001_initial"),
        ("user_sessions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cinemasession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cinema_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sessionmovie",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="movies.movie"
            ),
        ),
        migrations.AddField(
            model_name="sessionmovie",
            name="selected_release",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="movies.torrentrelease",
            ),
        ),
        migrations.AddField(
            model_name="sessionmovie",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session_movies",
                to="user_sessions.cinemasession",
            ),
        ),
        migrations.AddField(
            model_name="cinemasession",
            name="theme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user_sessions.sessiontheme",
            ),
        ),
        migrations.AddIndex(
            model_name="sessionmovie",
            index=models.Index(
                fields=["session", "order"], name="session_mov_session_4dc0c4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sessionmovie",
            unique_together={("session", "movie")},
        ),
        migrations.AddIndex(
            model_name="cinemasession",
            index=models.Index(
                fields=["user", "scheduled_date"], name="cinema_sess_user_id_b2d83a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cinemasession",
            index=models.Index(fields=["status"], name="cinema_sess_status_18ee14_idx"),
        ),
        migrations.AddIndex(
            model_name="cinemasession",
            index=models.Index(
                fields=["scheduled_date"], name="cinema_sess_schedul_a09662_idx"
            ),
        ),
    ]
