# Generated by Django 5.0.14 on 2026-09-06 18:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_sessions', '0003_sessionparticipant_sessionmessage_sessioninvite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionPoll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=300)),
                ('closed', models.BooleanField(default=False)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='user_sessions.sessionmessage')),
            ],
        ),
        migrations.CreateModel(
            name='SessionPollOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='user_sessions.sessionpoll')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SessionPollVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='user_sessions.sessionpolloption')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to='user_sessions.sessionparticipant')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='user_sessions.sessionpoll')),
            ],
        ),
        migrations.AddConstraint(
            model_name='sessionpollvote',
            constraint=models.UniqueConstraint(fields=('poll', 'participant'), name='um_voto_por_pessoa_por_enquete'),
        ),
    ]
