version: '3.8'

services:
  # Banco de Dados com suporte a Vetores (Essencial para o ML)
  db:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_USER: lumiere
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lumiere_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Cache e Filas de Tarefas (Celery)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data: