[pytest]
# Informe ao pytest para usar o plugin django
DJANGO_SETTINGS_MODULE = lumiere.settings

# pythonpath deve apontar para a pasta que contém os apps
pythonpath = backend

# O pulo do gato: adicione -p pytest_django se ele não carregar sozinho
addopts = -p pytest_django --strict-markers

python_files = test.py tests.py test_*.py *_test.py *_tests.py
testpaths = backend

markers =
    django_db: mark test to need database access
