# Generated by Django 5.2.11 on 2026-04-09 18:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enable_in_app", models.BooleanField(default=True)),
                ("enable_email", models.BooleanField(default=True)),
                ("email_session_reminders", models.BooleanField(default=True)),
                ("email_downloads", models.BooleanField(default=True)),
                ("email_recommendations", models.BooleanField(default=False)),
                ("email_weekly_digest", models.BooleanField(default=True)),
                ("enable_push", models.BooleanField(default=False)),
                ("push_session_reminders", models.BooleanField(default=True)),
                ("push_downloads", models.BooleanField(default=True)),
                (
                    "digest_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("never", "Never"),
                        ],
                        default="weekly",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notification_preferences",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("session_ready", "Session Ready"),
                            ("session_reminder", "Session Reminder"),
                            ("download_complete", "Download Complete"),
                            ("download_failed", "Download Failed"),
                            ("letterboxd_synced", "Letterboxd Synced"),
                            ("recommendation_new", "New Recommendations"),
                            ("movie_added_plex", "Movie Added to Plex"),
                            ("system", "System Notification"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("action_url", models.CharField(blank=True, max_length=500)),
                ("action_text", models.CharField(blank=True, max_length=100)),
                ("related_session_id", models.UUIDField(blank=True, null=True)),
                ("related_movie_id", models.UUIDField(blank=True, null=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("dismissed", models.BooleanField(default=False)),
                ("sent_email", models.BooleanField(default=False)),
                ("sent_push", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="notificatio_user_id_611c58_idx",
                    ),
                    models.Index(
                        fields=["user", "read"], name="notificatio_user_id_1f75db_idx"
                    ),
                    models.Index(fields=["type"], name="notificatio_type_8a8a78_idx"),
                ],
            },
        ),
    ]
