# Generated by Django 5.2.11 on 2026-04-10 13:27
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        CreateExtension('vector'),
    ]
