# Generated by Django 5.0.14 on 2026-09-01 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jellyfin_server_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='jellyfin_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='jellyfin_user_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
