# Generated by Django 5.0.14 on 2026-09-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_jellyfin_server_url_user_jellyfin_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='opensubtitles_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='opensubtitles_token',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='user',
            name='opensubtitles_username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
