# Generated by Django 5.0.14 on 2026-09-01 20:05

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_opensubtitles_api_key_user_opensubtitles_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='taste_profile_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
