# Generated by Django 5.0.14 on 2026-09-01 23:26

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_taste_profile_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='taste_profile_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
