# Generated by Django 5.0.14 on 2026-09-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_taste_profile_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='torrent_cache_bytes',
            field=models.BigIntegerField(default=10737418240),
        ),
        migrations.AddField(
            model_name='user',
            name='torrent_direto_permitido',
            field=models.BooleanField(default=False),
        ),
    ]
