# Generated by Django 5.0.14 on 2026-09-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_torrent_cache_bytes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jellyfin_verificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='plex_verificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
