# Generated by Django 5.2.11 on 2026-05-04 20:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("key", models.CharField(max_length=64, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("can_read", models.BooleanField(default=True)),
                ("can_write", models.BooleanField(default=False)),
                ("can_delete", models.BooleanField(default=False)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("total_requests", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "api_keys",
                "ordering": ["-created_at"],
            },
        ),
    ]
