# Generated by Django 5.0.14 on 2026-09-18 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecucaoDeTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarefa', models.CharField(db_index=True, max_length=255)),
                ('task_id', models.CharField(max_length=64, unique=True)),
                ('iniciada_em', models.DateTimeField(db_index=True)),
                ('terminada_em', models.DateTimeField(blank=True, null=True)),
                ('duracao_s', models.FloatField(blank=True, db_index=True, null=True)),
                ('sucesso', models.BooleanField(blank=True, help_text='Nulo enquanto está rodando.', null=True)),
                ('erro', models.TextField(blank=True)),
                ('origem', models.CharField(choices=[('beat', 'Agendada'), ('manual', 'Disparada à mão'), ('outro', 'Outra')], default='outro', max_length=10)),
                ('disparada_por', models.ForeignKey(blank=True, help_text='Só quando alguém apertou o botão no painel.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_disparadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'execucoes_de_tarefa',
                'ordering': ['-iniciada_em'],
                'indexes': [models.Index(fields=['tarefa', '-iniciada_em'], name='execucoes_d_tarefa_cf7dc0_idx'), models.Index(fields=['-iniciada_em', 'sucesso'], name='execucoes_d_iniciad_8bcab6_idx')],
            },
        ),
    ]
