/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description ViewSet para usuários */
        post: operations["auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/token/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials.
         */
        post: operations["auth_token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["auth_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/token/verify/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a token and indicates if it is valid.  This view provides no
         *     information about a token's fitness for a particular use.
         */
        post: operations["auth_token_verify_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/ws-ticket/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Ticket de uso único, válido por 30s, para abrir o WebSocket. */
        post: operations["auth_ws_ticket_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Estado do banco, do Redis e dos workers do Celery. */
        get: operations["health_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/movies/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ViewSet para filmes - MOTOR HÍBRIDO DEFINITIVO (Trigramas + Força-Bruta) */
        get: operations["movies_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/movies/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ViewSet para filmes - MOTOR HÍBRIDO DEFINITIVO (Trigramas + Força-Bruta) */
        get: operations["movies_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/movies/{id}/playback/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Resolve onde tocar o filme, na ordem Real-Debrid > Jellyfin > Plex. Devolve a primeira fonte que responder. */
        get: operations["movies_playback_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/movies/{id}/recommendations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ViewSet para filmes - MOTOR HÍBRIDO DEFINITIVO (Trigramas + Força-Bruta) */
        get: operations["movies_recommendations_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/movies/{id}/search_torrents/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description ViewSet para filmes - MOTOR HÍBRIDO DEFINITIVO (Trigramas + Força-Bruta) */
        post: operations["movies_search_torrents_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/movies/available/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ViewSet para filmes - MOTOR HÍBRIDO DEFINITIVO (Trigramas + Força-Bruta) */
        get: operations["movies_available_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/movies/top_rated/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ViewSet para filmes - MOTOR HÍBRIDO DEFINITIVO (Trigramas + Força-Bruta) */
        get: operations["movies_top_rated_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/movies/with_releases/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ViewSet para filmes - MOTOR HÍBRIDO DEFINITIVO (Trigramas + Força-Bruta) */
        get: operations["movies_with_releases_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/telemetry/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Agregações de telemetria do perfil. O corpo é um objeto montado dinamicamente a partir das consultas de agregação. */
        get: operations["profile_telemetry_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/releases/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["releases_list"];
        put?: never;
        post: operations["releases_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/releases/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["releases_retrieve"];
        put: operations["releases_update"];
        post?: never;
        delete: operations["releases_destroy"];
        options?: never;
        head?: never;
        patch: operations["releases_partial_update"];
        trace?: never;
    };
    "/api/releases/{id}/add_to_realdebrid/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["releases_add_to_realdebrid_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schema/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description OpenApi3 schema for this API. Format can be selected via content negotiation.
         *
         *     - YAML: application/vnd.oai.openapi
         *     - JSON: application/vnd.oai.openapi+json
         */
        get: operations["schema_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ViewSet para sessões de cinema */
        get: operations["sessions_list"];
        put?: never;
        /** @description ViewSet para sessões de cinema */
        post: operations["sessions_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ViewSet para sessões de cinema */
        get: operations["sessions_retrieve"];
        /** @description ViewSet para sessões de cinema */
        put: operations["sessions_update"];
        post?: never;
        /** @description ViewSet para sessões de cinema */
        delete: operations["sessions_destroy"];
        options?: never;
        head?: never;
        /** @description ViewSet para sessões de cinema */
        patch: operations["sessions_partial_update"];
        trace?: never;
    };
    "/api/sessions/{id}/add_movie/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Adiciona filme à sessão */
        post: operations["sessions_add_movie_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{id}/complete/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Completa a sessão */
        post: operations["sessions_complete_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{id}/prepare/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description ViewSet para sessões de cinema */
        post: operations["sessions_prepare_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{id}/start/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description ViewSet para sessões de cinema */
        post: operations["sessions_start_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/past/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Sessões passadas */
        get: operations["sessions_past_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/upcoming/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Sessões futuras (próximos 30 dias) */
        get: operations["sessions_upcoming_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/themes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ViewSet para temas pré-definidos */
        get: operations["themes_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/themes/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ViewSet para temas pré-definidos */
        get: operations["themes_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ViewSet para usuários */
        get: operations["users_list"];
        put?: never;
        /** @description ViewSet para usuários */
        post: operations["users_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ViewSet para usuários */
        get: operations["users_retrieve"];
        /** @description ViewSet para usuários */
        put: operations["users_update"];
        post?: never;
        /** @description ViewSet para usuários */
        delete: operations["users_destroy"];
        options?: never;
        head?: never;
        /** @description ViewSet para usuários */
        patch: operations["users_partial_update"];
        trace?: never;
    };
    "/api/users/connect_letterboxd/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Conecta conta Letterboxd */
        post: operations["users_connect_letterboxd_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Retorna usuário atual */
        get: operations["users_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/taste_profile/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Retorna perfil de gosto do usuário */
        get: operations["users_taste_profile_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Serializer unificado e otimizado contra queries N+1 */
        CinemaSession: {
            /** Format: uuid */
            id?: string;
            name: string;
            description?: string;
            emoji?: string;
            /** Format: date-time */
            scheduled_date: string;
            readonly status: components["schemas"]["StatusEnum"];
            theme_type: components["schemas"]["ThemeTypeEnum"];
            readonly theme: components["schemas"]["SessionTheme"];
            readonly movie_count: number;
            /** Format: uri */
            readonly first_movie_poster: string | null;
            readonly preparation_progress: number;
            readonly download_progress: number;
            estimated_duration_minutes?: number | null;
            readonly all_downloads_ready: boolean;
            readonly all_movies_selected: boolean;
            playlist_created?: boolean;
            readonly session_movies: components["schemas"]["SessionMovie"][] | null;
            movie_ids?: string[];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description * `pending` - Pending
         *     * `searching` - Searching
         *     * `found` - Found
         *     * `downloading` - Downloading
         *     * `ready` - Ready
         *     * `failed` - Failed
         * @enum {string}
         */
        DownloadStatusEnum: "pending" | "searching" | "found" | "downloading" | "ready" | "failed";
        HealthCheck: {
            status: string;
            checks: {
                [key: string]: string;
            };
        };
        Movie: {
            /** Format: uuid */
            id?: string;
            title: string;
            original_title?: string;
            alternative_titles?: unknown;
            year?: number | null;
            length_minutes?: number | null;
            country?: string;
            countries?: string[];
            spoken_languages?: string[];
            color?: string;
            genres?: string[];
            primary_genre?: string;
            themes?: string[];
            moods?: string[];
            keywords?: string[];
            /** @description R, PG-13, etc */
            mpaa_rating?: string;
            /** @description Premiações e Festivais (ex: Cannes, Oscars) */
            festivals?: unknown;
            director?: string;
            co_directors?: string[];
            cinematographer?: string | null;
            composer?: string | null;
            writer?: string | null;
            /** @description Atores e personagens */
            cast?: unknown;
            /** @description Equipe técnica principal */
            crew?: unknown;
            production_companies?: string[];
            tspdt_id?: string | null;
            /** @description Ranking mais recente */
            ranking_current?: number | null;
            /** @description Ex: {'2008': 100, '2025': 45} */
            tspdt_history?: unknown;
            imdb_id?: string | null;
            tmdb_id?: number | null;
            letterboxd_id?: string | null;
            overview?: string;
            tagline?: string;
            /** Format: uri */
            poster_url?: string;
            /** Format: uri */
            background_url?: string;
            /** Format: uri */
            trailer_url?: string;
            /** Format: uri */
            logo_url?: string | null;
            collection_name?: string | null;
            /** Format: int64 */
            budget?: number | null;
            /** Format: int64 */
            revenue?: number | null;
            /** Format: decimal */
            tmdb_rating?: string | null;
            tmdb_vote_count?: number | null;
            /** Format: decimal */
            imdb_rating?: string | null;
            imdb_vote_count?: number | null;
            /** Format: decimal */
            letterboxd_rating?: string | null;
            streaming_providers?: unknown;
            in_plex?: boolean;
            in_realdebrid?: boolean;
            available_instantly?: boolean;
            best_quality_available?: string;
            current_quality_score?: number | null;
            upgradeable?: boolean;
            view_count?: number;
            search_count?: number;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            /** Format: date-time */
            last_checked?: string | null;
            /** Format: date-time */
            metadata_updated_at?: string | null;
            /** @description Evita gastar cota da API OMDb duas vezes no mesmo filme */
            omdb_checked?: boolean;
            rotten_tomatoes_rating?: string | null;
            metacritic_rating?: string | null;
            /** @description Texto bruto do OMDb. Ex: Won 3 Oscars... */
            awards_summary?: string | null;
            wikidata_id?: string | null;
            /** @description ID oficial da MUBI */
            mubi_id?: string | null;
            aspect_ratio?: string | null;
            filming_locations?: string[];
            /** @description Passed / Failed / etc */
            bechdel_status?: string | null;
            wikidata_checked?: boolean;
        };
        /**
         * @description Serializer pesado para a página individual do filme.
         *     Expõe todo o modelo menos o embedding, então o frontend já recebe:
         *     - cast (Atores com fotos)
         *     - alternative_titles (Outros nomes do filme)
         *     - budget & revenue (Orçamento e Bilheteria)
         *     - tspdt_history (O gráfico histórico de evolução do filme)
         */
        MovieDetail: {
            /** Format: uuid */
            id?: string;
            readonly current_ranking: number | null;
            readonly best_releases: components["schemas"]["TorrentRelease"][];
            readonly similar_movies: components["schemas"]["SimilarMovie"][];
            title: string;
            original_title?: string;
            alternative_titles?: unknown;
            year?: number | null;
            length_minutes?: number | null;
            country?: string;
            countries?: string[];
            spoken_languages?: string[];
            color?: string;
            genres?: string[];
            primary_genre?: string;
            themes?: string[];
            moods?: string[];
            keywords?: string[];
            /** @description R, PG-13, etc */
            mpaa_rating?: string;
            /** @description Premiações e Festivais (ex: Cannes, Oscars) */
            festivals?: unknown;
            director?: string;
            co_directors?: string[];
            cinematographer?: string | null;
            composer?: string | null;
            writer?: string | null;
            /** @description Atores e personagens */
            cast?: unknown;
            /** @description Equipe técnica principal */
            crew?: unknown;
            production_companies?: string[];
            tspdt_id?: string | null;
            /** @description Ranking mais recente */
            ranking_current?: number | null;
            /** @description Ex: {'2008': 100, '2025': 45} */
            tspdt_history?: unknown;
            imdb_id?: string | null;
            tmdb_id?: number | null;
            letterboxd_id?: string | null;
            overview?: string;
            tagline?: string;
            /** Format: uri */
            poster_url?: string;
            /** Format: uri */
            background_url?: string;
            /** Format: uri */
            trailer_url?: string;
            /** Format: uri */
            logo_url?: string | null;
            collection_name?: string | null;
            /** Format: int64 */
            budget?: number | null;
            /** Format: int64 */
            revenue?: number | null;
            /** Format: decimal */
            tmdb_rating?: string | null;
            tmdb_vote_count?: number | null;
            /** Format: decimal */
            imdb_rating?: string | null;
            imdb_vote_count?: number | null;
            /** Format: decimal */
            letterboxd_rating?: string | null;
            streaming_providers?: unknown;
            in_plex?: boolean;
            in_realdebrid?: boolean;
            available_instantly?: boolean;
            best_quality_available?: string;
            current_quality_score?: number | null;
            upgradeable?: boolean;
            view_count?: number;
            search_count?: number;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            /** Format: date-time */
            last_checked?: string | null;
            /** Format: date-time */
            metadata_updated_at?: string | null;
            /** @description Evita gastar cota da API OMDb duas vezes no mesmo filme */
            omdb_checked?: boolean;
            rotten_tomatoes_rating?: string | null;
            metacritic_rating?: string | null;
            /** @description Texto bruto do OMDb. Ex: Won 3 Oscars... */
            awards_summary?: string | null;
            wikidata_id?: string | null;
            /** @description ID oficial da MUBI */
            mubi_id?: string | null;
            aspect_ratio?: string | null;
            filming_locations?: string[];
            /** @description Passed / Failed / etc */
            bechdel_status?: string | null;
            wikidata_checked?: boolean;
        };
        /**
         * @description Serializer otimizado para as listas (Home e Library).
         *     Traz apenas o essencial para montar cards bonitos e ricos em detalhes visuais,
         *     mas deixa listas gigantes (cast, alternative_titles) de fora para não pesar a rede.
         */
        MovieList: {
            /** Format: uuid */
            id?: string;
            title: string;
            original_title?: string;
            overview?: string;
            year?: number | null;
            director?: string;
            /** Format: uri */
            poster_url?: string;
            /** @description Ranking mais recente */
            ranking_current?: number | null;
            /** Format: decimal */
            tmdb_rating?: string | null;
            length_minutes?: number | null;
            /** Format: uri */
            background_url?: string;
            country?: string;
            tagline?: string;
            in_plex?: boolean;
            genres?: string[];
            /** Format: uri */
            trailer_url?: string;
            /** Format: uri */
            logo_url?: string | null;
            cinematographer?: string | null;
            composer?: string | null;
            writer?: string | null;
            streaming_providers?: unknown;
            /** @description R, PG-13, etc */
            mpaa_rating?: string;
            color?: string;
            collection_name?: string | null;
        };
        PaginatedCinemaSessionList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["CinemaSession"][];
        };
        PaginatedMovieListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["MovieList"][];
        };
        PaginatedSessionThemeList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["SessionTheme"][];
        };
        PaginatedTorrentReleaseList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["TorrentRelease"][];
        };
        PaginatedUserList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["User"][];
        };
        /** @description Serializer unificado e otimizado contra queries N+1 */
        PatchedCinemaSession: {
            /** Format: uuid */
            id?: string;
            name?: string;
            description?: string;
            emoji?: string;
            /** Format: date-time */
            scheduled_date?: string;
            readonly status?: components["schemas"]["StatusEnum"];
            theme_type?: components["schemas"]["ThemeTypeEnum"];
            readonly theme?: components["schemas"]["SessionTheme"];
            readonly movie_count?: number;
            /** Format: uri */
            readonly first_movie_poster?: string | null;
            readonly preparation_progress?: number;
            readonly download_progress?: number;
            estimated_duration_minutes?: number | null;
            readonly all_downloads_ready?: boolean;
            readonly all_movies_selected?: boolean;
            playlist_created?: boolean;
            readonly session_movies?: components["schemas"]["SessionMovie"][] | null;
            movie_ids?: string[];
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        PatchedTorrentRelease: {
            /** Format: uuid */
            id?: string;
            info_hash?: string;
            title?: string;
            /** Format: int64 */
            size_bytes?: number;
            /** Format: double */
            readonly size_gb?: number;
            resolution?: string;
            is_remux?: boolean;
            is_4k?: boolean;
            has_hdr?: boolean;
            has_dolby_vision?: boolean;
            video_codec?: string;
            audio_codec?: string;
            has_atmos?: boolean;
            has_dtsx?: boolean;
            audio_channels?: string;
            release_group?: string;
            seeders?: number;
            leechers?: number;
            readonly quality_score?: number;
            readonly video_score?: number;
            readonly audio_score?: number;
            readonly hdr_score?: number;
            instantly_available?: boolean;
            in_realdebrid?: boolean;
            realdebrid_status?: string;
            realdebrid_progress?: number;
            /** Format: date-time */
            readonly found_at?: string;
        };
        /** @description Serializer básico de usuário */
        PatchedUser: {
            /** Format: uuid */
            readonly id?: string;
            /**
             * Usuário
             * @description Obrigatório. 150 caracteres ou menos. Letras, números e @/./+/-/_ apenas.
             */
            username?: string;
            /**
             * Endereço de email
             * Format: email
             */
            email?: string;
            display_name?: string;
            /** Format: uri */
            avatar_url?: string;
            bio?: string;
            readonly is_premium?: boolean;
            /** Format: date-time */
            premium_until?: string | null;
            letterboxd_username?: string | null;
            letterboxd_connected?: boolean;
            /** Format: uri */
            plex_server_url?: string;
            readonly taste_profile_exists?: boolean;
            /**
             * Data de registro
             * Format: date-time
             */
            readonly date_joined?: string;
        };
        /** @description Fonte de reprodução resolvida na ordem Real-Debrid > Jellyfin > Plex. */
        PlaybackSource: {
            source: components["schemas"]["SourceEnum"];
            /** Format: uri */
            stream_url: string;
            label: string;
            container: string | null;
            quality: string;
        };
        /** @description Serializer para filmes dentro de uma sessão */
        SessionMovie: {
            /** Format: uuid */
            id?: string;
            readonly movie: components["schemas"]["MovieList"];
            /** Format: uuid */
            movie_id: string;
            order: number;
            readonly selected_release: components["schemas"]["TorrentRelease"];
            download_status?: components["schemas"]["DownloadStatusEnum"];
            download_progress?: number;
            notes?: string;
        };
        /** @description Serializer para temas de sessão */
        SessionTheme: {
            /** Format: uuid */
            id?: string;
            name: string;
            description?: string;
            emoji?: string;
            genres?: string[];
            countries?: string[];
            decades?: number[];
            directors?: string[];
            moods?: string[];
            keywords?: string[];
            is_predefined?: boolean;
            /** Format: date-time */
            readonly created_at: string;
        };
        /** @description Forma de cada item de MovieDetailSerializer.similar_movies. */
        SimilarMovie: {
            readonly movie: components["schemas"]["MovieList"];
            /** Format: double */
            readonly similarity: number;
            readonly type: string;
        };
        /**
         * @description * `realdebrid` - realdebrid
         *     * `jellyfin` - jellyfin
         *     * `plex` - plex
         * @enum {string}
         */
        SourceEnum: "realdebrid" | "jellyfin" | "plex";
        /**
         * @description * `planning` - Planning
         *     * `preparing` - Preparing
         *     * `ready` - Ready
         *     * `in_progress` - In Progress
         *     * `completed` - Completed
         *     * `cancelled` - Cancelled
         * @enum {string}
         */
        StatusEnum: "planning" | "preparing" | "ready" | "in_progress" | "completed" | "cancelled";
        /**
         * @description * `predefined` - Predefined
         *     * `custom` - Custom
         *     * `ai_generated` - AI Generated
         * @enum {string}
         */
        ThemeTypeEnum: "predefined" | "custom" | "ai_generated";
        TokenObtainPair: {
            username: string;
            password: string;
            readonly access: string;
            readonly refresh: string;
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        TokenVerify: {
            token: string;
        };
        TorrentRelease: {
            /** Format: uuid */
            id?: string;
            info_hash: string;
            title: string;
            /** Format: int64 */
            size_bytes: number;
            /** Format: double */
            readonly size_gb: number;
            resolution?: string;
            is_remux?: boolean;
            is_4k?: boolean;
            has_hdr?: boolean;
            has_dolby_vision?: boolean;
            video_codec?: string;
            audio_codec?: string;
            has_atmos?: boolean;
            has_dtsx?: boolean;
            audio_channels?: string;
            release_group?: string;
            seeders?: number;
            leechers?: number;
            readonly quality_score: number;
            readonly video_score: number;
            readonly audio_score: number;
            readonly hdr_score: number;
            instantly_available?: boolean;
            in_realdebrid?: boolean;
            realdebrid_status?: string;
            realdebrid_progress?: number;
            /** Format: date-time */
            readonly found_at: string;
        };
        /** @description Serializer básico de usuário */
        User: {
            /** Format: uuid */
            readonly id: string;
            /**
             * Usuário
             * @description Obrigatório. 150 caracteres ou menos. Letras, números e @/./+/-/_ apenas.
             */
            username: string;
            /**
             * Endereço de email
             * Format: email
             */
            email?: string;
            display_name?: string;
            /** Format: uri */
            avatar_url?: string;
            bio?: string;
            readonly is_premium: boolean;
            /** Format: date-time */
            premium_until?: string | null;
            letterboxd_username?: string | null;
            letterboxd_connected?: boolean;
            /** Format: uri */
            plex_server_url?: string;
            readonly taste_profile_exists: boolean;
            /**
             * Data de registro
             * Format: date-time
             */
            readonly date_joined: string;
        };
        /** @description Serializer para registro de novo usuário */
        UserRegistration: {
            /**
             * Usuário
             * @description Obrigatório. 150 caracteres ou menos. Letras, números e @/./+/-/_ apenas.
             */
            username: string;
            /**
             * Endereço de email
             * Format: email
             */
            email?: string;
            password: string;
            password_confirm: string;
            display_name?: string;
        };
        WebSocketTicket: {
            ticket: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRegistration"];
                "application/x-www-form-urlencoded": components["schemas"]["UserRegistration"];
                "multipart/form-data": components["schemas"]["UserRegistration"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRegistration"];
                };
            };
        };
    };
    auth_token_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainPair"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenObtainPair"];
                "multipart/form-data": components["schemas"]["TokenObtainPair"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenObtainPair"];
                };
            };
        };
    };
    auth_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefresh"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefresh"];
                "multipart/form-data": components["schemas"]["TokenRefresh"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    auth_token_verify_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenVerify"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenVerify"];
                "multipart/form-data": components["schemas"]["TokenVerify"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenVerify"];
                };
            };
        };
    };
    auth_ws_ticket_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebSocketTicket"];
                };
            };
        };
    };
    health_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthCheck"];
                };
            };
        };
    };
    movies_list: {
        parameters: {
            query?: {
                available_instantly?: boolean;
                category?: string;
                country?: string;
                curations?: string;
                decades?: string;
                director?: string;
                genres?: string;
                in_plex?: boolean;
                /** @description Qual campo usar ao ordenar os resultados. */
                ordering?: string;
                /** @description Um número de página dentro do conjunto de resultados paginado. */
                page?: number;
                qualities?: string;
                search?: string;
                year?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedMovieListList"];
                };
            };
        };
    };
    movies_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um string UUID que identifica este movie. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovieDetail"];
                };
            };
        };
    };
    movies_playback_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um string UUID que identifica este movie. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaybackSource"];
                };
            };
            /** @description Nenhuma fonte tem este filme. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    movies_recommendations_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um string UUID que identifica este movie. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Movie"];
                };
            };
        };
    };
    movies_search_torrents_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um string UUID que identifica este movie. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Movie"];
                "application/x-www-form-urlencoded": components["schemas"]["Movie"];
                "multipart/form-data": components["schemas"]["Movie"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Movie"];
                };
            };
        };
    };
    movies_available_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Movie"];
                };
            };
        };
    };
    movies_top_rated_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Movie"];
                };
            };
        };
    };
    movies_with_releases_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Movie"];
                };
            };
        };
    };
    profile_telemetry_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    releases_list: {
        parameters: {
            query?: {
                has_atmos?: boolean;
                in_realdebrid?: boolean;
                instantly_available?: boolean;
                is_remux?: boolean;
                movie?: string;
                /** @description Qual campo usar ao ordenar os resultados. */
                ordering?: string;
                /** @description Um número de página dentro do conjunto de resultados paginado. */
                page?: number;
                resolution?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTorrentReleaseList"];
                };
            };
        };
    };
    releases_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TorrentRelease"];
                "application/x-www-form-urlencoded": components["schemas"]["TorrentRelease"];
                "multipart/form-data": components["schemas"]["TorrentRelease"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TorrentRelease"];
                };
            };
        };
    };
    releases_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um string UUID que identifica este torrent release. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TorrentRelease"];
                };
            };
        };
    };
    releases_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um string UUID que identifica este torrent release. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TorrentRelease"];
                "application/x-www-form-urlencoded": components["schemas"]["TorrentRelease"];
                "multipart/form-data": components["schemas"]["TorrentRelease"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TorrentRelease"];
                };
            };
        };
    };
    releases_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um string UUID que identifica este torrent release. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    releases_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um string UUID que identifica este torrent release. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedTorrentRelease"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedTorrentRelease"];
                "multipart/form-data": components["schemas"]["PatchedTorrentRelease"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TorrentRelease"];
                };
            };
        };
    };
    releases_add_to_realdebrid_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um string UUID que identifica este torrent release. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TorrentRelease"];
                "application/x-www-form-urlencoded": components["schemas"]["TorrentRelease"];
                "multipart/form-data": components["schemas"]["TorrentRelease"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TorrentRelease"];
                };
            };
        };
    };
    schema_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "yaml";
                lang?: "af" | "ar" | "ar-dz" | "ast" | "az" | "be" | "bg" | "bn" | "br" | "bs" | "ca" | "ckb" | "cs" | "cy" | "da" | "de" | "dsb" | "el" | "en" | "en-au" | "en-gb" | "eo" | "es" | "es-ar" | "es-co" | "es-mx" | "es-ni" | "es-ve" | "et" | "eu" | "fa" | "fi" | "fr" | "fy" | "ga" | "gd" | "gl" | "he" | "hi" | "hr" | "hsb" | "hu" | "hy" | "ia" | "id" | "ig" | "io" | "is" | "it" | "ja" | "ka" | "kab" | "kk" | "km" | "kn" | "ko" | "ky" | "lb" | "lt" | "lv" | "mk" | "ml" | "mn" | "mr" | "ms" | "my" | "nb" | "ne" | "nl" | "nn" | "os" | "pa" | "pl" | "pt" | "pt-br" | "ro" | "ru" | "sk" | "sl" | "sq" | "sr" | "sr-latn" | "sv" | "sw" | "ta" | "te" | "tg" | "th" | "tk" | "tr" | "tt" | "udm" | "ug" | "uk" | "ur" | "uz" | "vi" | "zh-hans" | "zh-hant";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.oai.openapi": {
                        [key: string]: unknown;
                    };
                    "application/yaml": {
                        [key: string]: unknown;
                    };
                    "application/vnd.oai.openapi+json": {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    sessions_list: {
        parameters: {
            query?: {
                /** @description Um número de página dentro do conjunto de resultados paginado. */
                page?: number;
                /**
                 * @description * `planning` - Planning
                 *     * `preparing` - Preparing
                 *     * `ready` - Ready
                 *     * `in_progress` - In Progress
                 *     * `completed` - Completed
                 *     * `cancelled` - Cancelled
                 */
                status?: "cancelled" | "completed" | "in_progress" | "planning" | "preparing" | "ready";
                /**
                 * @description * `predefined` - Predefined
                 *     * `custom` - Custom
                 *     * `ai_generated` - AI Generated
                 */
                theme_type?: "ai_generated" | "custom" | "predefined";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCinemaSessionList"];
                };
            };
        };
    };
    sessions_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CinemaSession"];
                "application/x-www-form-urlencoded": components["schemas"]["CinemaSession"];
                "multipart/form-data": components["schemas"]["CinemaSession"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CinemaSession"];
                };
            };
        };
    };
    sessions_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um string UUID que identifica este cinema session. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CinemaSession"];
                };
            };
        };
    };
    sessions_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um string UUID que identifica este cinema session. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CinemaSession"];
                "application/x-www-form-urlencoded": components["schemas"]["CinemaSession"];
                "multipart/form-data": components["schemas"]["CinemaSession"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CinemaSession"];
                };
            };
        };
    };
    sessions_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um string UUID que identifica este cinema session. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    sessions_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um string UUID que identifica este cinema session. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCinemaSession"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCinemaSession"];
                "multipart/form-data": components["schemas"]["PatchedCinemaSession"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CinemaSession"];
                };
            };
        };
    };
    sessions_add_movie_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um string UUID que identifica este cinema session. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CinemaSession"];
                "application/x-www-form-urlencoded": components["schemas"]["CinemaSession"];
                "multipart/form-data": components["schemas"]["CinemaSession"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CinemaSession"];
                };
            };
        };
    };
    sessions_complete_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um string UUID que identifica este cinema session. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CinemaSession"];
                "application/x-www-form-urlencoded": components["schemas"]["CinemaSession"];
                "multipart/form-data": components["schemas"]["CinemaSession"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CinemaSession"];
                };
            };
        };
    };
    sessions_prepare_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um string UUID que identifica este cinema session. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CinemaSession"];
                "application/x-www-form-urlencoded": components["schemas"]["CinemaSession"];
                "multipart/form-data": components["schemas"]["CinemaSession"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CinemaSession"];
                };
            };
        };
    };
    sessions_start_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um string UUID que identifica este cinema session. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CinemaSession"];
                "application/x-www-form-urlencoded": components["schemas"]["CinemaSession"];
                "multipart/form-data": components["schemas"]["CinemaSession"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CinemaSession"];
                };
            };
        };
    };
    sessions_past_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CinemaSession"];
                };
            };
        };
    };
    sessions_upcoming_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CinemaSession"];
                };
            };
        };
    };
    themes_list: {
        parameters: {
            query?: {
                /** @description Qual campo usar ao ordenar os resultados. */
                ordering?: string;
                /** @description Um número de página dentro do conjunto de resultados paginado. */
                page?: number;
                /** @description Um termo de busca. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSessionThemeList"];
                };
            };
        };
    };
    themes_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um string UUID que identifica este session theme. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionTheme"];
                };
            };
        };
    };
    users_list: {
        parameters: {
            query?: {
                /** @description Qual campo usar ao ordenar os resultados. */
                ordering?: string;
                /** @description Um número de página dentro do conjunto de resultados paginado. */
                page?: number;
                /** @description Um termo de busca. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedUserList"];
                };
            };
        };
    };
    users_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRegistration"];
                "application/x-www-form-urlencoded": components["schemas"]["UserRegistration"];
                "multipart/form-data": components["schemas"]["UserRegistration"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRegistration"];
                };
            };
        };
    };
    users_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um string UUID que identifica este user. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um string UUID que identifica este user. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["User"];
                "application/x-www-form-urlencoded": components["schemas"]["User"];
                "multipart/form-data": components["schemas"]["User"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um string UUID que identifica este user. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um string UUID que identifica este user. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUser"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUser"];
                "multipart/form-data": components["schemas"]["PatchedUser"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_connect_letterboxd_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["User"];
                "application/x-www-form-urlencoded": components["schemas"]["User"];
                "multipart/form-data": components["schemas"]["User"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_taste_profile_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
}
