# Generated by Django 5.2.11 on 2026-05-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="letterboxdlist",
            name="sync_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
