# Generated by Django 5.2.11 on 2026-05-05 13:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0003_letterboxdlist_sync_enabled"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="letterboxdlistitem",
            options={"ordering": ["position"]},
        ),
        migrations.AddField(
            model_name="letterboxddiary",
            name="film_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="letterboxddiary",
            name="film_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="letterboxddiary",
            name="letterboxd_entry_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="letterboxddiary",
            name="letterboxd_uri",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="letterboxddiary",
            name="like",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="letterboxddiary",
            name="review",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="letterboxddiary",
            name="rewatch",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="letterboxddiary",
            name="watched_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="letterboxdlist",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="letterboxdlist",
            name="film_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="letterboxdlist",
            name="letterboxd_list_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="letterboxdlist",
            name="letterboxd_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="letterboxdlistitem",
            name="film_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="letterboxdlistitem",
            name="film_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="letterboxdlistitem",
            name="letterboxd_film_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="letterboxdlistitem",
            name="position",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="letterboxddiary",
            unique_together={("user", "letterboxd_entry_id")},
        ),
        migrations.AlterUniqueTogether(
            name="letterboxdlist",
            unique_together={("user", "letterboxd_list_id")},
        ),
    ]
