# Generated by Django 5.2.11 on 2026-04-17 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ml", "0001_initial"),
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovieSimilarity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "similarity_score",
                    models.FloatField(help_text="Score de 0-1 indicando similaridade"),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarities",
                        to="movies.movie",
                    ),
                ),
                (
                    "similar_movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similar_to",
                        to="movies.movie",
                    ),
                ),
            ],
            options={
                "db_table": "movie_similarities",
                "ordering": ["-similarity_score"],
                "unique_together": {("movie", "similar_movie")},
            },
        ),
    ]
