# Generated by Django 5.2.11 on 2026-05-04 20:44

import datetime
import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ml", "0002_initial"),
        ("movies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="moviesimilarity",
            options={"ordering": ["-overall_similarity"]},
        ),
        migrations.AddField(
            model_name="moviesimilarity",
            name="content_similarity",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="moviesimilarity",
            name="model_version",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="moviesimilarity",
            name="overall_similarity",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="moviesimilarity",
            name="similarity_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="usertasteprofile",
            name="average_rating",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="usertasteprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 5, 4, 20, 44, 52, 556002, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usertasteprofile",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=384, null=True
            ),
        ),
        migrations.AddField(
            model_name="usertasteprofile",
            name="embedding_model",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="usertasteprofile",
            name="favorite_decades",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="usertasteprofile",
            name="favorite_directors",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="usertasteprofile",
            name="favorite_genres",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="usertasteprofile",
            name="needs_retraining",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usertasteprofile",
            name="profile_confidence",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="usertasteprofile",
            name="rating_distribution",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="usertasteprofile",
            name="total_films_watched",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usertasteprofile",
            name="total_ratings",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usertasteprofile",
            name="training_samples",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="moviesimilarity",
            name="similarity_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(default=0.0)),
                ("reason", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.movie"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-score"],
                "unique_together": {("user", "movie")},
            },
        ),
    ]
