# Generated by Django 5.0.14 on 2026-05-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0003_alter_moviesimilarity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='confidence',
            field=models.FloatField(default=0.5),
        ),
    ]
