# Generated by Django 5.0.14 on 2026-09-04 14:27

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0004_recommendation_confidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertasteprofile',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True),
        ),
        migrations.AlterField(
            model_name='usertasteprofile',
            name='taste_profile_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True),
        ),
    ]
