# Generated by Django 5.2.11 on 2026-05-04 20:23

import uuid

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import pgvector.django.vector
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        TrigramExtension(),
        
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("original_title", models.CharField(blank=True, max_length=500)),
                ("year", models.IntegerField()),
                ("director", models.CharField(max_length=500)),
                (
                    "co_directors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=200)),
                (
                    "countries",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        default=list,
                        size=None,
                    ),
                ),
                ("length_minutes", models.IntegerField(blank=True, null=True)),
                ("color", models.CharField(blank=True, max_length=10)),
                (
                    "genres",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        default=list,
                        size=None,
                    ),
                ),
                ("primary_genre", models.CharField(blank=True, max_length=100)),
                (
                    "themes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "moods",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "keywords",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("ranking_2026", models.IntegerField(blank=True, null=True)),
                ("ranking_2025", models.IntegerField(blank=True, null=True)),
                ("tspdt_id", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "imdb_id",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("tmdb_id", models.IntegerField(blank=True, null=True, unique=True)),
                (
                    "letterboxd_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("tmdb_data", models.JSONField(blank=True, default=dict)),
                ("overview", models.TextField(blank=True)),
                ("tagline", models.CharField(blank=True, max_length=500)),
                ("poster_url", models.URLField(blank=True)),
                ("backdrop_url", models.URLField(blank=True)),
                ("cast", models.JSONField(blank=True, default=list)),
                ("crew", models.JSONField(blank=True, default=list)),
                (
                    "tmdb_rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("tmdb_vote_count", models.IntegerField(blank=True, null=True)),
                (
                    "imdb_rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "letterboxd_rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=768, null=True
                    ),
                ),
                ("embedding_model", models.CharField(blank=True, max_length=100)),
                ("in_plex", models.BooleanField(default=False)),
                ("in_realdebrid", models.BooleanField(default=False)),
                ("available_instantly", models.BooleanField(default=False)),
                (
                    "best_quality_available",
                    models.CharField(blank=True, max_length=100),
                ),
                ("current_quality_score", models.IntegerField(blank=True, null=True)),
                ("upgradeable", models.BooleanField(default=False)),
                ("view_count", models.IntegerField(default=0)),
                ("search_count", models.IntegerField(default=0)),
                (
                    "average_user_rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_checked", models.DateTimeField(blank=True, null=True)),
                ("metadata_updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ranking_2026", "year"],
                        name="movies_movi_ranking_013a74_idx",
                    ),
                    models.Index(
                        fields=["year", "director"], name="movies_movi_year_67e84d_idx"
                    ),
                    models.Index(
                        fields=["primary_genre", "year"],
                        name="movies_movi_primary_a6c314_idx",
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["genres"], name="movies_movi_genres_c0d66b_gin"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["keywords"], name="movies_movi_keyword_afd773_gin"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["title"],
                        name="movie_search_idx",
                        opclasses=["gin_trgm_ops"],
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TorrentRelease",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("info_hash", models.CharField(max_length=40, unique=True)),
                ("title", models.CharField(max_length=500)),
                ("size_bytes", models.BigIntegerField()),
                ("magnet_link", models.TextField(blank=True)),
                ("indexer_id", models.IntegerField(blank=True, null=True)),
                ("indexer_name", models.CharField(blank=True, max_length=100)),
                ("resolution", models.CharField(blank=True, max_length=20)),
                ("is_remux", models.BooleanField(default=False)),
                ("is_4k", models.BooleanField(default=False)),
                ("has_hdr", models.BooleanField(default=False)),
                ("has_hdr10_plus", models.BooleanField(default=False)),
                ("has_dolby_vision", models.BooleanField(default=False)),
                ("video_codec", models.CharField(blank=True, max_length=50)),
                ("video_bitrate_kbps", models.IntegerField(blank=True, null=True)),
                ("audio_codec", models.CharField(blank=True, max_length=100)),
                ("has_atmos", models.BooleanField(default=False)),
                ("has_dtsx", models.BooleanField(default=False)),
                ("has_truehd", models.BooleanField(default=False)),
                ("has_dts_hd_ma", models.BooleanField(default=False)),
                ("audio_channels", models.CharField(blank=True, max_length=10)),
                ("audio_bitrate_kbps", models.IntegerField(blank=True, null=True)),
                (
                    "audio_languages",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "subtitle_languages",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("has_hardcoded_subs", models.BooleanField(default=False)),
                ("release_group", models.CharField(blank=True, max_length=100)),
                ("release_type", models.CharField(blank=True, max_length=50)),
                ("is_scene", models.BooleanField(default=False)),
                ("edition", models.CharField(blank=True, max_length=100)),
                ("is_proper", models.BooleanField(default=False)),
                ("is_repack", models.BooleanField(default=False)),
                ("seeders", models.IntegerField(default=0)),
                ("leechers", models.IntegerField(default=0)),
                ("upload_date", models.DateTimeField(blank=True, null=True)),
                ("quality_score", models.IntegerField(default=0)),
                ("video_score", models.IntegerField(default=0)),
                ("audio_score", models.IntegerField(default=0)),
                ("hdr_score", models.IntegerField(default=0)),
                ("release_score", models.IntegerField(default=0)),
                ("seeds_score", models.IntegerField(default=0)),
                ("in_realdebrid", models.BooleanField(default=False)),
                ("realdebrid_id", models.CharField(blank=True, max_length=100)),
                ("realdebrid_status", models.CharField(blank=True, max_length=50)),
                ("realdebrid_progress", models.IntegerField(default=0)),
                ("realdebrid_added_at", models.DateTimeField(blank=True, null=True)),
                (
                    "realdebrid_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("realdebrid_links", models.JSONField(blank=True, default=list)),
                ("instantly_available", models.BooleanField(default=False)),
                ("instant_check_at", models.DateTimeField(blank=True, null=True)),
                ("found_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_seeder_check", models.DateTimeField(blank=True, null=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="torrent_releases",
                        to="movies.movie",
                    ),
                ),
            ],
            options={
                "db_table": "torrent_releases",
                "ordering": ["-quality_score", "-seeders"],
                "indexes": [
                    models.Index(
                        fields=["movie", "-quality_score"],
                        name="torrent_rel_movie_i_169a7f_idx",
                    ),
                    models.Index(
                        fields=["info_hash"], name="torrent_rel_info_ha_4a3e02_idx"
                    ),
                    models.Index(
                        fields=["resolution", "is_remux", "has_atmos"],
                        name="torrent_rel_resolut_bc0a6a_idx",
                    ),
                    models.Index(
                        fields=["instantly_available"],
                        name="torrent_rel_instant_cb7018_idx",
                    ),
                ],
            },
        ),
    ]
