# Generated by Django 5.0.14 on 2026-05-07 15:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='movie',
            name='movies_movi_ranking_013a74_idx',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='ranking_2025',
            new_name='imdb_vote_count',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='average_user_rating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='background_url',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='ranking_2026',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tmdb_data',
        ),
        migrations.AddField(
            model_name='movie',
            name='background_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='movie',
            name='budget',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='collection_name',
            field=models.CharField(blank=True, help_text='Ex: The Lord of the Rings Collection', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='mpaa_rating',
            field=models.CharField(blank=True, help_text='R, PG-13, etc', max_length=20),
        ),
        migrations.AddField(
            model_name='movie',
            name='production_companies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='movie',
            name='ranking_current',
            field=models.IntegerField(blank=True, help_text='Ranking mais recente (ex: 2026)', null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='revenue',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='spoken_languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='movie',
            name='tspdt_history',
            field=models.JSONField(blank=True, default=dict, help_text="Histórico completo de rankings ex: {'2008': 100, '2025': 45}"),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.JSONField(blank=True, default=list, help_text='Atores e personagens'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='countries',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='movie',
            name='crew',
            field=models.JSONField(blank=True, default=list, help_text='Equipe técnica principal'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmdb_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tspdt_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['ranking_current', 'year'], name='movies_movi_ranking_a8dbdb_idx'),
        ),
    ]
