# Generated by Django 5.0.14 on 2026-05-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20260508_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='collection_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='ranking_current',
            field=models.IntegerField(blank=True, help_text='Ranking mais recente', null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tspdt_history',
            field=models.JSONField(blank=True, default=dict, help_text="Ex: {'2008': 100, '2025': 45}"),
        ),
    ]
