# Generated by Django 5.0.14 on 2026-05-09 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_collection_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='festivals',
            field=models.JSONField(blank=True, default=list, help_text='Premiações e Festivais (ex: Cannes, Oscars)'),
        ),
    ]
