# Generated by Django 5.0.14 on 2026-05-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movie_festivals'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='awards_summary',
            field=models.CharField(blank=True, help_text='Texto bruto do OMDb. Ex: Won 3 Oscars...', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='metacritic_rating',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='omdb_checked',
            field=models.BooleanField(default=False, help_text='Evita gastar cota da API OMDb duas vezes no mesmo filme'),
        ),
        migrations.AddField(
            model_name='movie',
            name='rotten_tomatoes_rating',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
