# Generated by Django 5.0.14 on 2026-05-10 00:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movie_awards_summary_movie_metacritic_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='aspect_ratio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='bechdel_status',
            field=models.CharField(blank=True, help_text='Passed / Failed / etc', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='filming_locations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='movie',
            name='mubi_id',
            field=models.CharField(blank=True, help_text='ID oficial da MUBI', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='wikidata_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
