# Generated by Django 5.0.14 on 2026-05-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_movie_aspect_ratio_movie_bechdel_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='wikidata_checked',
            field=models.BooleanField(default=False),
        ),
    ]
