# Generated by Django 5.0.14 on 2026-09-01 20:05

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_movie_wikidata_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
