# Generated by Django 5.0.14 on 2026-09-01 20:09

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_alter_movie_embedding'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movie',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='movie_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
    ]
