# Generated by Django 5.0.14 on 2026-09-01 23:26

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_movie_movie_embedding_hnsw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
