# Generated by Django 5.0.14 on 2026-09-04 14:08

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_alter_movie_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True),
        ),
    ]
