# Generated by Django 5.0.14 on 2026-09-05 21:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_alter_movie_embedding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_watched_at', models.DateTimeField(auto_now_add=True)),
                ('last_watched_at', models.DateTimeField(auto_now=True)),
                ('times_watched', models.PositiveIntegerField(default=0)),
                ('progress_seconds', models.PositiveIntegerField(default=0)),
                ('runtime_seconds', models.PositiveIntegerField(default=0, help_text='Duração real do arquivo, que costuma divergir do metadado.')),
                ('completed', models.BooleanField(default=False, help_text='Passou de FRACAO_PARA_CONCLUIR. É isto que a interface chama de "assistido".')),
                ('source', models.CharField(choices=[('player', 'Assistido no player'), ('letterboxd', 'Importado do diário Letterboxd'), ('manual', 'Marcado à mão')], default='player', max_length=20)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watches', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Watch histories',
                'indexes': [models.Index(fields=['user', 'completed'], name='movies_watc_user_id_59a12b_idx'), models.Index(fields=['user', '-last_watched_at'], name='movies_watc_user_id_4269fc_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='watchhistory',
            constraint=models.UniqueConstraint(fields=('user', 'movie'), name='um_registro_por_filme_por_usuario'),
        ),
    ]
