# Generated by Django 5.0.14 on 2026-09-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_watchhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cached_in_realdebrid',
            field=models.BooleanField(default=False),
        ),
    ]
