# Generated by Django 5.0.14 on 2026-09-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_filme_cacheado_no_realdebrid'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='plex_rating_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
