# Generated by Django 5.0.14 on 2026-09-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_plex_rating_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrentrelease',
            name='duration_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
