# Generated by Django 5.0.14 on 2026-09-10 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_torrentrelease_duration_seconds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='torrentrelease',
            name='pedido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloads_pedidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
