# Generated by Django 5.0.14 on 2026-09-10 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_torrentrelease_pedido_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='copias_buscadas_em',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
