# Generated by Django 5.0.14 on 2026-09-12 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_movie_copias_buscadas_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrentrelease',
            name='audio_tracks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
