# Generated by Django 5.0.14 on 2026-05-07 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawIngestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(default='TSPDT', max_length=50)),
                ('source_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('raw_data', models.JSONField(help_text='Dados brutos da fonte')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Processando'), ('COMPLETED', 'Concluído'), ('FAILED', 'Falhou')], db_index=True, default='PENDING', max_length=20)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Raw Ingestion',
                'verbose_name_plural': 'Raw Ingestions',
                'ordering': ['-created_at'],
            },
        ),
    ]
