# Generated by Django 5.0.14 on 2026-05-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawingestion',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Processando'), ('COMPLETED', 'Concluído'), ('FAILED', 'Falhou'), ('NON_FILM', 'Ignorado (Não-Filme)')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
